import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import Layout from "@/components/Layout";
import { pricingPlans, testimonials } from "@/lib/cosmic-data";
import {
  Star, Sparkles, Moon, BookOpen, Users, TrendingUp,
  Shield, Zap, Globe, Check, ArrowRight, Quote
} from "lucide-react";

// ─── Feature Data ─────────────────────────────────────────────

const features = [
  {
    icon: Sparkles,
    title: "AI-Powered Readings",
    description:
      "Receive deeply personalised astrology and cosmic ordering readings generated by advanced AI, tailored to your unique birth chart and intentions.",
    color: "text-violet-400",
    bg: "bg-violet-500/10",
  },
  {
    icon: Moon,
    title: "Moon Phase Tracker",
    description:
      "Stay in rhythm with lunar cycles. Get daily guidance on how the moon's energy affects your manifestations, relationships, and inner world.",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
  },
  {
    icon: BookOpen,
    title: "Cosmic Journal",
    description:
      "Capture your intentions, dreams, and reflections with AI-generated prompts aligned to your current planetary transits and moon phase.",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
  },
  {
    icon: Users,
    title: "Expert Practitioners",
    description:
      "Book live 1:1 sessions with vetted astrologers, tarot readers, and cosmic coaches for personal guidance when you need it most.",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
  },
  {
    icon: TrendingUp,
    title: "Manifestation Tracking",
    description:
      "Set cosmic intentions and track their materialisation over time. Visualise your manifestation journey with beautiful insight charts.",
    color: "text-green-400",
    bg: "bg-green-500/10",
  },
  {
    icon: Globe,
    title: "Cosmic Community",
    description:
      "Connect with thousands of like-minded souls on their cosmic journey. Share readings, celebrate wins, and support each other's growth.",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
  },
];

const steps = [
  {
    number: "01",
    title: "Create Your Cosmic Profile",
    description:
      "Enter your birth date, time, and location to generate your unique natal chart — the cosmic blueprint of your soul's journey.",
    icon: Star,
  },
  {
    number: "02",
    title: "Set Your Intentions",
    description:
      "Tell the universe what you desire. Our AI synthesises your birth chart with your current intentions to deliver precise cosmic guidance.",
    icon: Sparkles,
  },
  {
    number: "03",
    title: "Receive & Manifest",
    description:
      "Get personalised readings, journal prompts, and ritual guidance. Track your manifestations as they unfold in beautiful alignment.",
    icon: Moon,
  },
];

// ─── Sub-Components ───────────────────────────────────────────

function HeroSection() {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden gradient-cosmic">
      {/* Star field */}
      <div className="starfield" />

      {/* Decorative orbs */}
      <div className="absolute top-1/4 left-1/4 w-64 h-64 rounded-full bg-primary/10 blur-3xl animate-pulse" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 rounded-full bg-violet-600/10 blur-3xl animate-pulse" style={{ animationDelay: "1s" }} />
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] rounded-full bg-indigo-900/20 blur-3xl" />

      <div className="relative container text-center z-10 py-20">
        {/* Badge */}
        <div className="animate-fade-up flex justify-center mb-6">
          <Badge variant="outline" className="border-primary/50 bg-primary/10 text-primary px-4 py-1.5 text-sm gap-2">
            <Sparkles className="h-3.5 w-3.5" />
            Over 50,000 cosmic journeys started
          </Badge>
        </div>

        {/* Headline */}
        <h1
          className="text-5xl md:text-7xl font-bold text-white leading-tight mb-6"
          style={{ animationDelay: "0.1s" }}
        >
          Unlock the{" "}
          <span className="gradient-text">Wisdom</span>
          <br />
          of the{" "}
          <span className="gradient-text">Cosmos</span>
        </h1>

        {/* Sub-headline */}
        <p className="text-lg md:text-xl text-white/70 max-w-2xl mx-auto mb-10">
          AI-powered astrology readings, cosmic ordering guidance, and personalised
          moon rituals — all aligned to your unique birth chart and deepest desires.
        </p>

        {/* CTA Buttons */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
          <Link to="/onboarding">
            <Button size="lg" className="gap-2 text-base px-8 animate-pulse-glow">
              <Star className="h-4 w-4 fill-current" />
              Begin Your Journey Free
            </Button>
          </Link>
          <a href="#how-it-works">
            <Button size="lg" variant="outline" className="gap-2 text-base px-8 border-white/20 text-white bg-white/5 hover:bg-white/10">
              See How It Works
              <ArrowRight className="h-4 w-4" />
            </Button>
          </a>
        </div>

        {/* Social proof */}
        <div className="mt-12 flex flex-col sm:flex-row items-center justify-center gap-6 text-white/60 text-sm">
          <div className="flex items-center gap-2">
            <div className="flex -space-x-2">
              {["SL", "MC", "AO", "JK"].map((initials) => (
                <div
                  key={initials}
                  className="w-8 h-8 rounded-full bg-primary/60 border-2 border-background flex items-center justify-center text-xs font-bold text-white"
                >
                  {initials}
                </div>
              ))}
            </div>
            <span>50,000+ explorers</span>
          </div>
          <div className="hidden sm:block w-px h-4 bg-white/20" />
          <div className="flex items-center gap-1">
            {[...Array(5)].map((_, i) => (
              <Star key={i} className="h-3.5 w-3.5 fill-amber-400 text-amber-400" />
            ))}
            <span className="ml-1">4.9 / 5 from 12,000+ reviews</span>
          </div>
          <div className="hidden sm:block w-px h-4 bg-white/20" />
          <div className="flex items-center gap-1.5">
            <Shield className="h-3.5 w-3.5 text-green-400" />
            <span>No credit card required</span>
          </div>
        </div>
      </div>

      {/* Bottom fade */}
      <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-background to-transparent" />
    </section>
  );
}

function FeaturesSection() {
  return (
    <section id="features" className="py-24 container">
      <div className="text-center mb-16">
        <Badge variant="secondary" className="mb-4">Features</Badge>
        <h2 className="text-4xl font-bold mb-4">
          Everything You Need for Your{" "}
          <span className="gradient-text">Cosmic Journey</span>
        </h2>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          From AI-powered readings to live practitioner sessions, every tool you
          need to align with the universe is right here.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {features.map(({ icon: Icon, title, description, color, bg }) => (
          <Card key={title} className="group hover:shadow-lg hover:shadow-primary/10 hover:-translate-y-1 transition-all duration-300 glass-card">
            <CardHeader>
              <div className={`w-12 h-12 rounded-xl ${bg} flex items-center justify-center mb-4`}>
                <Icon className={`h-6 w-6 ${color}`} />
              </div>
              <h3 className="font-bold text-lg">{title}</h3>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground text-sm leading-relaxed">{description}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  );
}

function HowItWorksSection() {
  return (
    <section id="how-it-works" className="py-24 bg-muted/30">
      <div className="container">
        <div className="text-center mb-16">
          <Badge variant="secondary" className="mb-4">How It Works</Badge>
          <h2 className="text-4xl font-bold mb-4">
            Three Steps to{" "}
            <span className="gradient-text">Cosmic Alignment</span>
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Getting started takes less than five minutes. Your personalised cosmic
            experience begins the moment you share your birth details.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
          {/* Connecting line */}
          <div className="hidden md:block absolute top-12 left-[calc(16.67%+2rem)] right-[calc(16.67%+2rem)] h-px bg-gradient-to-r from-transparent via-primary/40 to-transparent" />

          {steps.map(({ number, title, description, icon: Icon }) => (
            <div key={number} className="flex flex-col items-center text-center">
              <div className="relative mb-6">
                <div className="w-24 h-24 rounded-full bg-primary/10 border border-primary/30 flex items-center justify-center animate-float" style={{ animationDelay: `${parseInt(number) * 0.3}s` }}>
                  <Icon className="h-8 w-8 text-primary" />
                </div>
                <div className="absolute -top-2 -right-2 w-8 h-8 rounded-full bg-primary text-primary-foreground text-xs font-bold flex items-center justify-center">
                  {number}
                </div>
              </div>
              <h3 className="font-bold text-xl mb-3">{title}</h3>
              <p className="text-muted-foreground leading-relaxed">{description}</p>
            </div>
          ))}
        </div>

        <div className="text-center mt-12">
          <Link to="/onboarding">
            <Button size="lg" className="gap-2">
              <Sparkles className="h-4 w-4" />
              Start Your Cosmic Profile
            </Button>
          </Link>
        </div>
      </div>
    </section>
  );
}

function PricingSection() {
  return (
    <section id="pricing" className="py-24 container">
      <div className="text-center mb-16">
        <Badge variant="secondary" className="mb-4">Pricing</Badge>
        <h2 className="text-4xl font-bold mb-4">
          Choose Your{" "}
          <span className="gradient-text">Cosmic Plan</span>
        </h2>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          Start free and upgrade whenever you're ready. All plans include our
          core cosmic tools with no hidden fees.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
        {pricingPlans.map((plan) => (
          <Card
            key={plan.id}
            className={`relative flex flex-col transition-all duration-300 hover:-translate-y-1 ${
              plan.highlighted
                ? "border-primary shadow-lg shadow-primary/20 bg-primary/5"
                : "glass-card"
            }`}
          >
            {plan.highlighted && (
              <div className="absolute -top-4 left-1/2 -translate-x-1/2">
                <Badge className="bg-primary text-primary-foreground px-4 py-1 gap-1">
                  <Zap className="h-3 w-3" />
                  Most Popular
                </Badge>
              </div>
            )}
            <CardHeader className="pb-4">
              <h3 className="font-bold text-xl">{plan.name}</h3>
              <p className="text-muted-foreground text-sm">{plan.description}</p>
              <div className="mt-4">
                <span className="text-4xl font-bold">
                  {plan.price === 0 ? "Free" : `$${plan.price}`}
                </span>
                {plan.price > 0 && (
                  <span className="text-muted-foreground text-sm ml-1">/ {plan.period}</span>
                )}
              </div>
            </CardHeader>
            <CardContent className="flex flex-col flex-1 gap-4">
              <ul className="space-y-2.5 flex-1">
                {plan.features.map((feature) => (
                  <li key={feature} className="flex items-start gap-2.5 text-sm">
                    <div className="mt-0.5 w-4 h-4 rounded-full bg-primary/20 flex items-center justify-center flex-shrink-0">
                      <Check className="h-2.5 w-2.5 text-primary" />
                    </div>
                    {feature}
                  </li>
                ))}
              </ul>
              <Link to="/onboarding" className="mt-4">
                <Button
                  className="w-full"
                  variant={plan.highlighted ? "default" : "outline"}
                >
                  {plan.cta}
                </Button>
              </Link>
            </CardContent>
          </Card>
        ))}
      </div>

      <p className="text-center text-muted-foreground text-sm mt-8">
        All plans include a 7-day money-back guarantee. No contracts, cancel anytime.
      </p>
    </section>
  );
}

function TestimonialsSection() {
  return (
    <section className="py-24 bg-muted/30">
      <div className="container">
        <div className="text-center mb-16">
          <Badge variant="secondary" className="mb-4">Testimonials</Badge>
          <h2 className="text-4xl font-bold mb-4">
            Voices from the{" "}
            <span className="gradient-text">Cosmic Community</span>
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {testimonials.map((t) => (
            <Card key={t.name} className="glass-card hover:shadow-lg hover:shadow-primary/10 transition-all">
              <CardContent className="pt-6">
                <Quote className="h-8 w-8 text-primary/40 mb-4" />
                <p className="text-sm leading-relaxed text-muted-foreground mb-6">
                  "{t.quote}"
                </p>
                <Separator className="mb-4" />
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-primary/20 text-primary font-bold text-sm flex items-center justify-center">
                    {t.avatar}
                  </div>
                  <div>
                    <p className="font-semibold text-sm">{t.name}</p>
                    <p className="text-xs text-muted-foreground">{t.role} · {t.sign}</p>
                  </div>
                </div>
                <div className="flex gap-0.5 mt-3">
                  {[...Array(t.stars)].map((_, i) => (
                    <Star key={i} className="h-3.5 w-3.5 fill-amber-400 text-amber-400" />
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}

function CtaSection() {
  return (
    <section className="py-24 container">
      <div className="relative rounded-3xl overflow-hidden gradient-cosmic p-12 md:p-16 text-center">
        <div className="starfield opacity-60" />
        <div className="relative z-10">
          <div className="text-6xl mb-6">✨</div>
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Your Cosmic Journey{" "}
            <span className="gradient-text">Awaits</span>
          </h2>
          <p className="text-white/70 text-lg max-w-xl mx-auto mb-8">
            Join over 50,000 cosmic explorers who have transformed their lives by
            aligning with the universe's infinite wisdom. Start free today.
          </p>
          <Link to="/onboarding">
            <Button size="lg" className="gap-2 text-base px-10 animate-pulse-glow">
              <Star className="h-4 w-4 fill-current" />
              Begin for Free — No Card Required
            </Button>
          </Link>
        </div>
      </div>
    </section>
  );
}

// ─── Page ─────────────────────────────────────────────────────

export default function Index() {
  return (
    <Layout variant="landing">
      <HeroSection />
      <FeaturesSection />
      <HowItWorksSection />
      <PricingSection />
      <TestimonialsSection />
      <CtaSection />
    </Layout>
  );
}
